
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'ActiveSection': typeof import("../components/ActiveSection.vue")['default']
    'Blog': typeof import("../components/Blog.vue")['default']
    'BlogClassic': typeof import("../components/BlogClassic.vue")['default']
    'BlogDetails': typeof import("../components/BlogDetails.vue")['default']
    'BlogDetailsClassic': typeof import("../components/BlogDetailsClassic.vue")['default']
    'Clients': typeof import("../components/Clients.vue")['default']
    'Contacts': typeof import("../components/Contacts.vue")['default']
    'Header': typeof import("../components/Header.vue")['default']
    'Knowledge': typeof import("../components/Knowledge.vue")['default']
    'PreLoader': typeof import("../components/PreLoader.vue")['default']
    'Quote': typeof import("../components/Quote.vue")['default']
    'SideBarContent': typeof import("../components/SideBarContent.vue")['default']
    'SocialLinks': typeof import("../components/SocialLinks.vue")['default']
    'TestimonialsSlider': typeof import("../components/TestimonialsSlider.vue")['default']
    'TypingAnimation': typeof import("../components/TypingAnimation.vue")['default']
    'Works': typeof import("../components/Works.vue")['default']
    'AboutMe': typeof import("../components/about/AboutMe.vue")['default']
    'AboutMe2': typeof import("../components/about/AboutMe2.vue")['default']
    'AboutFunFact': typeof import("../components/about/FunFact.vue")['default']
    'AboutPrice': typeof import("../components/about/Price.vue")['default']
    'AboutServices': typeof import("../components/about/Services.vue")['default']
    'BackgroundImage': typeof import("../components/background/BackgroundImage.vue")['default']
    'BackgroundGradientBG': typeof import("../components/background/GradientBG.vue")['default']
    'HomeIndex1': typeof import("../components/home/Index-1.vue")['default']
    'HomeIndexClassic': typeof import("../components/home/Index-classic.vue")['default']
    'HomeIndex2': typeof import("../components/home/index-2.vue")['default']
    'HomeIndex3': typeof import("../components/home/index-3.vue")['default']
    'HomeIndex4': typeof import("../components/home/index-4.vue")['default']
    'HomeIndex5': typeof import("../components/home/index-5.vue")['default']
    'HomeIndex6': typeof import("../components/home/index-6.vue")['default']
    'HomeIndex7': typeof import("../components/home/index-7.vue")['default']
    'HomeIndex8': typeof import("../components/home/index-8.vue")['default']
    'IsotopeFitnessIsotope': typeof import("../components/isotope/FitnessIsotope.vue")['default']
    'IsotopeLawyer': typeof import("../components/isotope/Lawyer.vue")['default']
    'IsotopeMusician': typeof import("../components/isotope/Musician.vue")['default']
    'IsotopeWriter': typeof import("../components/isotope/Writer.vue")['default']
    'PopupContentPopup': typeof import("../components/popup/ContentPopup.vue")['default']
    'PopupImgGallery': typeof import("../components/popup/ImgGallery.vue")['default']
    'PopupMfpPopup': typeof import("../components/popup/MfpPopup.vue")['default']
    'ResumeEducation': typeof import("../components/resume/Education.vue")['default']
    'ResumeExperience': typeof import("../components/resume/Experience.vue")['default']
    'Resume': typeof import("../components/resume/Resume.vue")['default']
    'SkillLanguages': typeof import("../components/skill/Languages.vue")['default']
    'SkillPorgressBar': typeof import("../components/skill/PorgressBar.vue")['default']
    'SkillPorgressCircle': typeof import("../components/skill/PorgressCircle.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyActiveSection': typeof import("../components/ActiveSection.vue")['default']
    'LazyBlog': typeof import("../components/Blog.vue")['default']
    'LazyBlogClassic': typeof import("../components/BlogClassic.vue")['default']
    'LazyBlogDetails': typeof import("../components/BlogDetails.vue")['default']
    'LazyBlogDetailsClassic': typeof import("../components/BlogDetailsClassic.vue")['default']
    'LazyClients': typeof import("../components/Clients.vue")['default']
    'LazyContacts': typeof import("../components/Contacts.vue")['default']
    'LazyHeader': typeof import("../components/Header.vue")['default']
    'LazyKnowledge': typeof import("../components/Knowledge.vue")['default']
    'LazyPreLoader': typeof import("../components/PreLoader.vue")['default']
    'LazyQuote': typeof import("../components/Quote.vue")['default']
    'LazySideBarContent': typeof import("../components/SideBarContent.vue")['default']
    'LazySocialLinks': typeof import("../components/SocialLinks.vue")['default']
    'LazyTestimonialsSlider': typeof import("../components/TestimonialsSlider.vue")['default']
    'LazyTypingAnimation': typeof import("../components/TypingAnimation.vue")['default']
    'LazyWorks': typeof import("../components/Works.vue")['default']
    'LazyAboutMe': typeof import("../components/about/AboutMe.vue")['default']
    'LazyAboutMe2': typeof import("../components/about/AboutMe2.vue")['default']
    'LazyAboutFunFact': typeof import("../components/about/FunFact.vue")['default']
    'LazyAboutPrice': typeof import("../components/about/Price.vue")['default']
    'LazyAboutServices': typeof import("../components/about/Services.vue")['default']
    'LazyBackgroundImage': typeof import("../components/background/BackgroundImage.vue")['default']
    'LazyBackgroundGradientBG': typeof import("../components/background/GradientBG.vue")['default']
    'LazyHomeIndex1': typeof import("../components/home/Index-1.vue")['default']
    'LazyHomeIndexClassic': typeof import("../components/home/Index-classic.vue")['default']
    'LazyHomeIndex2': typeof import("../components/home/index-2.vue")['default']
    'LazyHomeIndex3': typeof import("../components/home/index-3.vue")['default']
    'LazyHomeIndex4': typeof import("../components/home/index-4.vue")['default']
    'LazyHomeIndex5': typeof import("../components/home/index-5.vue")['default']
    'LazyHomeIndex6': typeof import("../components/home/index-6.vue")['default']
    'LazyHomeIndex7': typeof import("../components/home/index-7.vue")['default']
    'LazyHomeIndex8': typeof import("../components/home/index-8.vue")['default']
    'LazyIsotopeFitnessIsotope': typeof import("../components/isotope/FitnessIsotope.vue")['default']
    'LazyIsotopeLawyer': typeof import("../components/isotope/Lawyer.vue")['default']
    'LazyIsotopeMusician': typeof import("../components/isotope/Musician.vue")['default']
    'LazyIsotopeWriter': typeof import("../components/isotope/Writer.vue")['default']
    'LazyPopupContentPopup': typeof import("../components/popup/ContentPopup.vue")['default']
    'LazyPopupImgGallery': typeof import("../components/popup/ImgGallery.vue")['default']
    'LazyPopupMfpPopup': typeof import("../components/popup/MfpPopup.vue")['default']
    'LazyResumeEducation': typeof import("../components/resume/Education.vue")['default']
    'LazyResumeExperience': typeof import("../components/resume/Experience.vue")['default']
    'LazyResume': typeof import("../components/resume/Resume.vue")['default']
    'LazySkillLanguages': typeof import("../components/skill/Languages.vue")['default']
    'LazySkillPorgressBar': typeof import("../components/skill/PorgressBar.vue")['default']
    'LazySkillPorgressCircle': typeof import("../components/skill/PorgressCircle.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const ActiveSection: typeof import("../components/ActiveSection.vue")['default']
export const Blog: typeof import("../components/Blog.vue")['default']
export const BlogClassic: typeof import("../components/BlogClassic.vue")['default']
export const BlogDetails: typeof import("../components/BlogDetails.vue")['default']
export const BlogDetailsClassic: typeof import("../components/BlogDetailsClassic.vue")['default']
export const Clients: typeof import("../components/Clients.vue")['default']
export const Contacts: typeof import("../components/Contacts.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const Knowledge: typeof import("../components/Knowledge.vue")['default']
export const PreLoader: typeof import("../components/PreLoader.vue")['default']
export const Quote: typeof import("../components/Quote.vue")['default']
export const SideBarContent: typeof import("../components/SideBarContent.vue")['default']
export const SocialLinks: typeof import("../components/SocialLinks.vue")['default']
export const TestimonialsSlider: typeof import("../components/TestimonialsSlider.vue")['default']
export const TypingAnimation: typeof import("../components/TypingAnimation.vue")['default']
export const Works: typeof import("../components/Works.vue")['default']
export const AboutMe: typeof import("../components/about/AboutMe.vue")['default']
export const AboutMe2: typeof import("../components/about/AboutMe2.vue")['default']
export const AboutFunFact: typeof import("../components/about/FunFact.vue")['default']
export const AboutPrice: typeof import("../components/about/Price.vue")['default']
export const AboutServices: typeof import("../components/about/Services.vue")['default']
export const BackgroundImage: typeof import("../components/background/BackgroundImage.vue")['default']
export const BackgroundGradientBG: typeof import("../components/background/GradientBG.vue")['default']
export const HomeIndex1: typeof import("../components/home/Index-1.vue")['default']
export const HomeIndexClassic: typeof import("../components/home/Index-classic.vue")['default']
export const HomeIndex2: typeof import("../components/home/index-2.vue")['default']
export const HomeIndex3: typeof import("../components/home/index-3.vue")['default']
export const HomeIndex4: typeof import("../components/home/index-4.vue")['default']
export const HomeIndex5: typeof import("../components/home/index-5.vue")['default']
export const HomeIndex6: typeof import("../components/home/index-6.vue")['default']
export const HomeIndex7: typeof import("../components/home/index-7.vue")['default']
export const HomeIndex8: typeof import("../components/home/index-8.vue")['default']
export const IsotopeFitnessIsotope: typeof import("../components/isotope/FitnessIsotope.vue")['default']
export const IsotopeLawyer: typeof import("../components/isotope/Lawyer.vue")['default']
export const IsotopeMusician: typeof import("../components/isotope/Musician.vue")['default']
export const IsotopeWriter: typeof import("../components/isotope/Writer.vue")['default']
export const PopupContentPopup: typeof import("../components/popup/ContentPopup.vue")['default']
export const PopupImgGallery: typeof import("../components/popup/ImgGallery.vue")['default']
export const PopupMfpPopup: typeof import("../components/popup/MfpPopup.vue")['default']
export const ResumeEducation: typeof import("../components/resume/Education.vue")['default']
export const ResumeExperience: typeof import("../components/resume/Experience.vue")['default']
export const Resume: typeof import("../components/resume/Resume.vue")['default']
export const SkillLanguages: typeof import("../components/skill/Languages.vue")['default']
export const SkillPorgressBar: typeof import("../components/skill/PorgressBar.vue")['default']
export const SkillPorgressCircle: typeof import("../components/skill/PorgressCircle.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyActiveSection: typeof import("../components/ActiveSection.vue")['default']
export const LazyBlog: typeof import("../components/Blog.vue")['default']
export const LazyBlogClassic: typeof import("../components/BlogClassic.vue")['default']
export const LazyBlogDetails: typeof import("../components/BlogDetails.vue")['default']
export const LazyBlogDetailsClassic: typeof import("../components/BlogDetailsClassic.vue")['default']
export const LazyClients: typeof import("../components/Clients.vue")['default']
export const LazyContacts: typeof import("../components/Contacts.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyKnowledge: typeof import("../components/Knowledge.vue")['default']
export const LazyPreLoader: typeof import("../components/PreLoader.vue")['default']
export const LazyQuote: typeof import("../components/Quote.vue")['default']
export const LazySideBarContent: typeof import("../components/SideBarContent.vue")['default']
export const LazySocialLinks: typeof import("../components/SocialLinks.vue")['default']
export const LazyTestimonialsSlider: typeof import("../components/TestimonialsSlider.vue")['default']
export const LazyTypingAnimation: typeof import("../components/TypingAnimation.vue")['default']
export const LazyWorks: typeof import("../components/Works.vue")['default']
export const LazyAboutMe: typeof import("../components/about/AboutMe.vue")['default']
export const LazyAboutMe2: typeof import("../components/about/AboutMe2.vue")['default']
export const LazyAboutFunFact: typeof import("../components/about/FunFact.vue")['default']
export const LazyAboutPrice: typeof import("../components/about/Price.vue")['default']
export const LazyAboutServices: typeof import("../components/about/Services.vue")['default']
export const LazyBackgroundImage: typeof import("../components/background/BackgroundImage.vue")['default']
export const LazyBackgroundGradientBG: typeof import("../components/background/GradientBG.vue")['default']
export const LazyHomeIndex1: typeof import("../components/home/Index-1.vue")['default']
export const LazyHomeIndexClassic: typeof import("../components/home/Index-classic.vue")['default']
export const LazyHomeIndex2: typeof import("../components/home/index-2.vue")['default']
export const LazyHomeIndex3: typeof import("../components/home/index-3.vue")['default']
export const LazyHomeIndex4: typeof import("../components/home/index-4.vue")['default']
export const LazyHomeIndex5: typeof import("../components/home/index-5.vue")['default']
export const LazyHomeIndex6: typeof import("../components/home/index-6.vue")['default']
export const LazyHomeIndex7: typeof import("../components/home/index-7.vue")['default']
export const LazyHomeIndex8: typeof import("../components/home/index-8.vue")['default']
export const LazyIsotopeFitnessIsotope: typeof import("../components/isotope/FitnessIsotope.vue")['default']
export const LazyIsotopeLawyer: typeof import("../components/isotope/Lawyer.vue")['default']
export const LazyIsotopeMusician: typeof import("../components/isotope/Musician.vue")['default']
export const LazyIsotopeWriter: typeof import("../components/isotope/Writer.vue")['default']
export const LazyPopupContentPopup: typeof import("../components/popup/ContentPopup.vue")['default']
export const LazyPopupImgGallery: typeof import("../components/popup/ImgGallery.vue")['default']
export const LazyPopupMfpPopup: typeof import("../components/popup/MfpPopup.vue")['default']
export const LazyResumeEducation: typeof import("../components/resume/Education.vue")['default']
export const LazyResumeExperience: typeof import("../components/resume/Experience.vue")['default']
export const LazyResume: typeof import("../components/resume/Resume.vue")['default']
export const LazySkillLanguages: typeof import("../components/skill/Languages.vue")['default']
export const LazySkillPorgressBar: typeof import("../components/skill/PorgressBar.vue")['default']
export const LazySkillPorgressCircle: typeof import("../components/skill/PorgressCircle.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
