// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/11/2024, 3:59:54 AM
const configMerger = require("C:/Projects/ryantailwindcss-10/package/ryan/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Projects/ryantailwindcss-10/package/ryan/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/ryantailwindcss-10/package/ryan/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/ryantailwindcss-10/package/ryan/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/ryantailwindcss-10/package/ryan/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/ryantailwindcss-10/package/ryan/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/ryantailwindcss-10/package/ryan/plugins/**/*.{js,ts,mjs}","C:/Projects/ryantailwindcss-10/package/ryan/composables/**/*.{js,ts,mjs}","C:/Projects/ryantailwindcss-10/package/ryan/utils/**/*.{js,ts,mjs}","C:/Projects/ryantailwindcss-10/package/ryan/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/ryantailwindcss-10/package/ryan/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/ryantailwindcss-10/package/ryan/app.config.{js,ts,mjs}"] }));

module.exports = config
